"""
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brunos-ims"
version = "0.0.1"
description = "Bruno's IMS - python package for tests"
readme = "README.md"
authors = [ { name = "jackbruno1994" } ]
requires-python = ">=3.8"
"""
