[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brunos-ims"
version = "0.0.1"
description = "Bruno's Integrated Management System"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["brunos_ims"]
